#ifndef SOLIDSYSLOGSWITCHINGSENDERERRORS_H
#define SOLIDSYSLOGSWITCHINGSENDERERRORS_H

#include "ExternC.h"
#include "SolidSyslogError.h"

EXTERN_C_BEGIN

    enum SolidSyslogSwitchingSenderErrors
    {
        SWITCHINGSENDER_ERROR_NULL_CONFIG,
        SWITCHINGSENDER_ERROR_NULL_SENDERS,
        SWITCHINGSENDER_ERROR_NULL_SELECTOR,
        SWITCHINGSENDER_ERROR_POOL_EXHAUSTED,
        SWITCHINGSENDER_ERROR_UNKNOWN_DESTROY,
        SWITCHINGSENDER_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource SwitchingSenderErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGSWITCHINGSENDERERRORS_H */
