#ifndef SOLIDSYSLOGERRORS_H
#define SOLIDSYSLOGERRORS_H

#include "ExternC.h"
#include "SolidSyslogError.h"

EXTERN_C_BEGIN

    enum SolidSyslogErrors
    {
        SOLIDSYSLOG_ERROR_CREATE_NULL_CONFIG,
        SOLIDSYSLOG_ERROR_CREATE_NULL_BUFFER,
        SOLIDSYSLOG_ERROR_CREATE_NULL_SENDER,
        SOLIDSYSLOG_ERROR_CREATE_NULL_STORE,
        SOLIDSYSLOG_ERROR_LOG_NULL_MESSAGE,
        SOLIDSYSLOG_ERROR_LOG_NULL_HANDLE,
        SOLIDSYSLOG_ERROR_SERVICE_NULL_HANDLE,
        SOLIDSYSLOG_ERROR_POOL_EXHAUSTED,
        SOLIDSYSLOG_ERROR_UNKNOWN_DESTROY,
        SOLIDSYSLOG_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource SolidSyslogErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGERRORS_H */
