@version: 4.11

source s_udp {
    syslog(
        transport("udp")
        port(5514)
        keep-hostname(yes)
    );
};

destination d_file {
    file(
        "/var/log/syslog-ng/received.log"
        template("PRIORITY=${PRI} TIMESTAMP=${ISODATE} HOSTNAME=${HOST} APP_NAME=${PROGRAM} PROCID=${PID} MSGID=${MSGID} STRUCTURED_DATA=${SDATA} MSG=${MSG}\n")
        flush_lines(1)
        create-dirs(yes)
        perm(0644)
    );
};

destination d_file_udp {
    file(
        "/var/log/syslog-ng/received_udp.log"
        template("PRIORITY=${PRI} TIMESTAMP=${ISODATE} HOSTNAME=${HOST} APP_NAME=${PROGRAM} PROCID=${PID} MSGID=${MSGID} STRUCTURED_DATA=${SDATA} MSG=${MSG}\n")
        flush_lines(1)
        create-dirs(yes)
        perm(0644)
    );
};

log {
    source(s_udp);
    destination(d_file);
};

log {
    source(s_udp);
    destination(d_file_udp);
};
