#ifndef SOLIDSYSLOGMBEDTLSAESGCMPOLICYERRORS_H
#define SOLIDSYSLOGMBEDTLSAESGCMPOLICYERRORS_H

#include "ExternC.h"

EXTERN_C_BEGIN

    struct SolidSyslogErrorSource;

    enum SolidSyslogMbedTlsAesGcmPolicyErrors
    {
        MBEDTLSAESGCMPOLICY_ERROR_POOL_EXHAUSTED,
        MBEDTLSAESGCMPOLICY_ERROR_UNKNOWN_DESTROY,
        MBEDTLSAESGCMPOLICY_ERROR_BAD_CONFIG,
        MBEDTLSAESGCMPOLICY_ERROR_KEY_UNAVAILABLE,
        MBEDTLSAESGCMPOLICY_ERROR_NONCE_FAILED,
        MBEDTLSAESGCMPOLICY_ERROR_ENCRYPT_FAILED,
        MBEDTLSAESGCMPOLICY_ERROR_DECRYPT_FAILED,
        MBEDTLSAESGCMPOLICY_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource MbedTlsAesGcmPolicyErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGMBEDTLSAESGCMPOLICYERRORS_H */
