#ifndef SOLIDSYSLOGGETADDRINFORESOLVERERRORS_H
#define SOLIDSYSLOGGETADDRINFORESOLVERERRORS_H

#include "ExternC.h"

EXTERN_C_BEGIN

    struct SolidSyslogErrorSource;

    enum SolidSyslogGetAddrInfoResolverErrors
    {
        GETADDRINFORESOLVER_ERROR_POOL_EXHAUSTED,
        GETADDRINFORESOLVER_ERROR_UNKNOWN_DESTROY,
        GETADDRINFORESOLVER_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource GetAddrInfoResolverErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGGETADDRINFORESOLVERERRORS_H */
