#ifndef SOLIDSYSLOGOPENSSLAESGCMPOLICYERRORS_H
#define SOLIDSYSLOGOPENSSLAESGCMPOLICYERRORS_H

#include "ExternC.h"

EXTERN_C_BEGIN

    struct SolidSyslogErrorSource;

    enum SolidSyslogOpenSslAesGcmPolicyErrors
    {
        OPENSSLAESGCMPOLICY_ERROR_POOL_EXHAUSTED,
        OPENSSLAESGCMPOLICY_ERROR_UNKNOWN_DESTROY,
        OPENSSLAESGCMPOLICY_ERROR_BAD_CONFIG,
        OPENSSLAESGCMPOLICY_ERROR_KEY_UNAVAILABLE,
        OPENSSLAESGCMPOLICY_ERROR_NONCE_FAILED,
        OPENSSLAESGCMPOLICY_ERROR_ENCRYPT_FAILED,
        OPENSSLAESGCMPOLICY_ERROR_DECRYPT_FAILED,
        OPENSSLAESGCMPOLICY_ERROR_MAX
    };

    extern const struct SolidSyslogErrorSource OpenSslAesGcmPolicyErrorSource;

EXTERN_C_END

#endif /* SOLIDSYSLOGOPENSSLAESGCMPOLICYERRORS_H */
